"""3 migrate

Revision ID: 74177dd0690e
Revises: b61b030e2354
Create Date: 2023-06-26 15:59:08.437286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74177dd0690e'
down_revision = 'b61b030e2354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('date_of_employment',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('date_of_dismissal',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('date_of_dismissal',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('date_of_employment',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
