"""5 migrate

Revision ID: aa88eff78efe
Revises: 74177dd0690e
Create Date: 2023-06-27 05:45:39.518867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa88eff78efe'
down_revision = '74177dd0690e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('date_of_employment',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('date_of_dismissal',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('date_of_dismissal',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('date_of_employment',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
