"""2 migrate

Revision ID: b61b030e2354
Revises: a168d652f4e8
Create Date: 2023-06-26 15:51:09.105345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61b030e2354'
down_revision = 'a168d652f4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
